// A7 + spec §2.4 — resolveGifPlayback / describeGifPlayback.
// See [internal]specs/2026-09-12-2369-gif-playback-gating-design.md §2.1, §2.2, §4.
import { describe, it, expect } from 'vitest';
import {
  resolveGifPlayback,
  describeGifPlayback,
  REDUCE_MOTION_WRITES_GIF_PLAYBACK,
  type GifPlaybackMode,
  type GifPlaybackGate,
} from '@/renderer/utils/ui/gifPlayback';

const MODES: GifPlaybackMode[] = ['auto', 'always', 'hover'];
const BOOLS = [true, false] as const;

interface Case {
  mode: GifPlaybackMode;
  reduceAnimations: boolean;
  windowFocused: boolean;
  hovering: boolean;
}

// Generated by nested loops over the three enums plus the three booleans —
// deliberately NOT 24 hand-written literals, so the table cannot silently
// omit a combination. See A7 (spec §4): "resolveGifPlayback is total over
// {auto,always,hover} × {RM on,off} × {focused,unfocused} × {hovering,not}".
const cases: Case[] = [];
for (const mode of MODES) {
  for (const reduceAnimations of BOOLS) {
    for (const windowFocused of BOOLS) {
      for (const hovering of BOOLS) {
        cases.push({ mode, reduceAnimations, windowFocused, hovering });
      }
    }
  }
}

describe('resolveGifPlayback — A7 exhaustive table', () => {
  it('the generator itself produces exactly 24 distinct combinations', () => {
    expect(cases).toHaveLength(3 * 2 * 2 * 2);
    expect(cases).toHaveLength(24);
    const distinct = new Set(cases.map((c) => JSON.stringify(c)));
    expect(distinct.size).toBe(24);
  });

  it.each(cases)(
    'mode=$mode reduceAnimations=$reduceAnimations windowFocused=$windowFocused hovering=$hovering',
    ({ mode, reduceAnimations, windowFocused, hovering }) => {
      // Independent re-derivation of the spec §2.1 rule, NOT a call into the
      // resolver's own code path — this is what lets the assertion catch a
      // broken resolver instead of merely echoing whatever it does.
      //   gate = mode === 'auto' ? (reduceAnimations ? 'hover' : 'always') : mode
      //   surface = gate === 'hover' && !hovering ? 'still' : 'animated'
      //   playing = surface === 'animated' && windowFocused
      const expectedGate: GifPlaybackGate =
        mode === 'auto' ? (reduceAnimations ? 'hover' : 'always') : mode;
      const expectedSurface: 'animated' | 'still' =
        expectedGate === 'hover' && !hovering ? 'still' : 'animated';
      const expectedPlaying = expectedSurface === 'animated' && windowFocused;

      const verdict = resolveGifPlayback({ mode, reduceAnimations, hovering, windowFocused });

      expect(verdict).toEqual({
        surface: expectedSurface,
        playing: expectedPlaying,
        gate: expectedGate,
      });
    }
  );

  it('REDUCE_MOTION_WRITES_GIF_PLAYBACK is false — the structural-restore guarantee', () => {
    // Not decoration: a future refactor that starts writing this field on a
    // Reduce Animations toggle would break the "turning RM off re-derives the
    // prior behaviour" invariant (spec §2.1) and must fail here first.
    expect(REDUCE_MOTION_WRITES_GIF_PLAYBACK).toBe(false);
  });
});

describe('describeGifPlayback — spec §2.4 hint table', () => {
  it('auto + Reduce Animations off: following Reduce Animations, plays automatically', () => {
    expect(
      describeGifPlayback({ mode: 'auto', reduceAnimations: false, windowFocused: true })
    ).toBe('Following Reduce Animations: GIFs play automatically.');
  });

  it('auto + Reduce Animations on: following Reduce Animations, hover only', () => {
    expect(describeGifPlayback({ mode: 'auto', reduceAnimations: true, windowFocused: true })).toBe(
      'Following Reduce Animations: GIFs play on hover only.'
    );
  });

  it('always: always plays even with Reduce Animations on, regardless of RM', () => {
    for (const reduceAnimations of BOOLS) {
      expect(describeGifPlayback({ mode: 'always', reduceAnimations, windowFocused: true })).toBe(
        'GIFs always play, even with Reduce Animations on.'
      );
    }
  });

  it('hover: only plays on hover, regardless of RM', () => {
    for (const reduceAnimations of BOOLS) {
      expect(describeGifPlayback({ mode: 'hover', reduceAnimations, windowFocused: true })).toBe(
        'GIFs only play while you hover over them.'
      );
    }
  });

  it('the unfocused suffix is APPENDED, never substituted, for every mode', () => {
    for (const mode of MODES) {
      for (const reduceAnimations of BOOLS) {
        const focused = describeGifPlayback({ mode, reduceAnimations, windowFocused: true });
        const unfocused = describeGifPlayback({ mode, reduceAnimations, windowFocused: false });

        // The base sentence must still be a substring when unfocused — proving
        // the suffix is appended rather than the sentence being replaced.
        expect(unfocused.startsWith(focused)).toBe(true);
        expect(unfocused).toBe(`${focused} Currently paused because Concord isn't focused.`);
      }
    }
  });
});
