import type { ForgeConfig } from '@electron-forge/shared-types';
import { MakerSquirrel } from '@electron-forge/maker-squirrel';
import { MakerZIP } from '@electron-forge/maker-zip';
import { MakerDMG } from '@electron-forge/maker-dmg';
import { MakerDeb } from '@electron-forge/maker-deb';
import { MakerRpm } from '@electron-forge/maker-rpm';
import { MakerAppImage } from '@reforged/maker-appimage';
import fs from 'fs';

// macOS signing & notarization — active only when CI provides all required env vars.
// Local developer builds without these env vars produce unsigned .app bundles.
//
// Per the Electron Forge signing docs (https://www.electronforge.io/guides/
// code-signing/code-signing-macos), `osxSign: {}` — empty object — is the
// recommended default. @electron/osx-sign ships a tested-in-the-wild set of
// entitlements (https://github.com/electron/osx-sign/tree/main/entitlements)
// and per-file signing logic for Electron's nested helper apps. We previously
// tried overriding these defaults via `optionsForFile` + a custom entitlements
// plist and hit a silent codesign hang during outer-bundle signing; trusting
// the defaults resolves it (see issue #403 debugging history).
//
// Forge auto-detects the signing identity by scanning the keychain for a
// `Developer ID Application` cert, so the identity string does not need to
// be hardcoded as long as exactly one such cert is imported.
const macSigning: Pick<
  NonNullable<ForgeConfig['packagerConfig']>,
  'osxSign' | 'osxNotarize'
> = process.env.APPLE_API_KEY && process.env.APPLE_API_KEY_ID && process.env.APPLE_API_ISSUER
  ? {
      osxSign: {},
      osxNotarize: {
        // App Store Connect API-key notarization (#825). Replaces the
        // app-specific-password path, which silently invalidated under
        // Apple-ID 2FA events and stranded users on 0.1.29.
        // APPLE_API_KEY here is a filesystem PATH to the .p8 key file —
        // CI writes it to a temp file in a darwin-only setup step; the
        // raw .p8 contents live in the GHA secret of the same name.
        tool: 'notarytool',
        appleApiKey: process.env.APPLE_API_KEY,
        appleApiKeyId: process.env.APPLE_API_KEY_ID,
        appleApiIssuer: process.env.APPLE_API_ISSUER,
      },
    }
  : {};

// electron-updater needs app-update.yml in Resources. The file is generated
// by CI (build-desktop.yml) before packaging. Include it only when present
// so local dev builds don't fail.
const extraResource: string[] = [];
if (fs.existsSync('./app-update.yml')) {
  extraResource.push('./app-update.yml');
}
// Third-party NOTICE/attribution file (per docs/legal/dependency-license-audit.md
// F-1). MIT, BSD, Apache-2.0, ISC, MPL-2.0, and CC-BY-licensed dependencies
// require attribution in the distributed artifact. NOTICE.md lives at the
// repo root; the relative path from this file is ../../NOTICE.md. Include
// conditionally so local builds that don't have the repo-root layout don't
// fail (e.g., extracted-tarball dev workflows).
if (fs.existsSync('../../NOTICE.md')) {
  extraResource.push('../../NOTICE.md');
}
// Forensic build tag (#920 §5.13). Generated by scripts/generate-buildtag.mjs
// from CONCORD_BUILD_TAG before packaging (renamed from VITE_BUILD_TAG to
// avoid Vite's `import.meta.env` exposure path per Copilot review on PR #982).
// Absent in local dev builds → main process falls back to 'unknown'
// (see src/main/buildInfo.ts).
//
// The "packaging context" discriminator narrows the fail-loud guard below
// to actual electron-forge invocations (`electron-forge package` / `make`).
// Unit tests (e.g. `packagingIdentity.test.ts`) also import forge.config.ts
// to inspect identity fields — those imports have no `electron-forge` in
// `process.argv`, so they don't trip the guard. This avoids a self-induced
// test failure where the CI test job (CI=true, vitest loading the config)
// would otherwise throw before any test ran.
// System tray icons (#1099). Committed static assets; extraResource copies the
// directory to <Resources>/tray/ in packaged builds (consumed by
// resolveTrayIconPath in src/main/tray.ts). existsSync-guarded for consistency
// with the entries above.
if (fs.existsSync('./assets/tray')) {
  extraResource.push('./assets/tray');
}
const isForgePackaging = process.argv.some((arg) => arg.includes('electron-forge'));
if (fs.existsSync('./buildtag.json')) {
  extraResource.push('./buildtag.json');
} else if (process.env.CI === 'true' && isForgePackaging) {
  // Fail-loud in CI packaging: a production build without buildtag.json
  // ships blind to incident-response (the IPC channel returns 'unknown'
  // regardless of which release it is). The packaging workflow has a
  // dedicated `Generate buildtag.json` step that runs between `npm run
  // build` and forge make; if we're here, that step was skipped or
  // failed silently. (#920 §5.13 silent-failure-hunter F3.)
  throw new Error(
    'forge.config.ts: buildtag.json missing in CI packaging context. ' +
      'Run `npm run build:buildtag` before electron-forge make/package, or ' +
      'check that the workflow Configure-build-environment step set CONCORD_BUILD_TAG (#920 §5.13).'
  );
}
// Google OAuth non-confidential client_secret (#975). Generated by
// scripts/generate-google-client-secret.mjs before packaging. Read
// MAIN-process-only via process.resourcesPath (never renderer/VITE_).
// Absent locally → main process falls back to env GOOGLE_OAUTH_CLIENT_SECRET_DESKTOP.
if (fs.existsSync('./googleClientSecret.json')) {
  extraResource.push('./googleClientSecret.json');
} else if (process.env.CI === 'true' && process.env.GOOGLE_SSO_DESKTOP_REQUIRED === 'true') {
  throw new Error(
    'forge.config.ts: googleClientSecret.json missing in CI packaging with GOOGLE_SSO_DESKTOP_REQUIRED=true. ' +
      'Run `npm run build:gclientsecret` before forge make/package (see build-desktop.yml).'
  );
}

const linuxIconConfig = () => ({
  '128x128': './build/icons/128x128.png',
  '256x256': './build/icons/256x256.png',
  '512x512': './build/icons/512x512.png',
});

const config: ForgeConfig = {
  packagerConfig: {
    asar: {
      // Exclude source maps from the packaged ASAR archive. Source maps must
      // NOT ship to end users — they expose full source code and any secrets
      // or logic embedded in it.
      unpackDir: undefined,
    },
    ignore: [/\.map$/],
    name: 'Concord Voice',
    // Per-platform executable name (#1077 follow-up).
    //
    // macOS / Windows: use the proper display name 'Concord Voice'. This is
    // what users see in Activity Monitor (macOS), Task Manager (Windows), and
    // crash reports — proper-name format is the user-facing expectation on
    // those platforms.
    //
    // Linux: fall back to kebab-case 'concord-voice'. Two structural reasons:
    //   (1) debian-policy §5.6.7 expects lowercase alphanumeric + hyphens for
    //       binary names placed under /usr/bin/. Spaces work in the filesystem
    //       but break shell completion, $PATH lookups, and most process-
    //       management scripts.
    //   (2) @reforged/maker-appimage's `bin:` option performs a literal-string
    //       file lookup inside the packaged app directory. With
    //       `bin: 'concord-voice'` (the Linux convention we keep in the Deb /
    //       Rpm / AppImage maker configs below) but executableName set to
    //       'Concord Voice', the lookup fails at make-time with "Could not
    //       find executable 'concord-voice' in packaged application." Aligning
    //       executableName to bin on Linux closes that gap.
    //
    // `process.platform` reflects the BUILDER's OS, not the target. This is
    // correct in CI (each platform builds on its native runner per
    // build-desktop.yml: ubuntu-latest for Linux, macos-latest for macOS,
    // windows-latest for Windows). It would break for cross-compilation
    // (e.g., `electron-forge make --platform=linux` on macOS would produce a
    // Linux package with executableName='Concord Voice' because the builder
    // is macOS). Cross-compilation isn't used by the project; if that
    // changes, refactor to derive the target from argv instead.
    executableName: process.platform === 'linux' ? 'concord-voice' : 'Concord Voice',
    icon: './build/icon',
    appBundleId: 'com.concordvoice.desktop',
    protocols: [{ name: 'Concord Voice invite links', schemes: ['concord'] }],
    appCopyright: 'Copyright © 2026 Concord Voice LLC',
    appCategoryType: 'public.app-category.social-networking',
    win32metadata: {
      CompanyName: 'Concord Voice LLC',
      FileDescription: 'Concord Voice Desktop Client',
      ProductName: 'Concord Voice',
    },
    extraResource,
    ...macSigning,
    darwinDarkModeSupport: true,
    extendInfo: {
      CFBundleURLTypes: [
        {
          CFBundleURLName: 'Concord Voice invite links',
          CFBundleURLSchemes: ['concord'],
        },
      ],
      NSMicrophoneUsageDescription:
        'Concord Voice needs microphone access for voice calls and audio communication.',
      NSCameraUsageDescription: 'Concord Voice needs camera access for video calls.',
    },
  },
  makers: [
    new MakerSquirrel({
      name: 'ConcordVoice',
      setupExe: 'ConcordVoiceSetup.exe',
      setupIcon: './build/icon.ico',
      loadingGif: './build/splash.gif',
      iconUrl: 'https://concordvoice.com/icon.ico',
      description: 'Concord Voice Desktop Client - Privacy-first voice communication',
      copyright: 'Copyright © 2026 Concord Voice LLC. All rights reserved.',
      owners: 'Concord Voice LLC',
    }),
    new MakerZIP({}, ['darwin']),
    // DMG installer (#1159 Phase 1) — branded drag-to-Applications experience.
    // ZIP above remains the canonical artifact for electron-updater's auto-update
    // chain (see latest-mac.yml generator in .github/workflows/build-desktop.yml).
    // The .dmg is install-only; do NOT add it to the latest-mac.yml glob.
    new MakerDMG(
      {
        background: './build/dmg-background.png',
        icon: './build/icon.icns',
        format: 'ULFO',
        // Icon centers per design handoff spec
        // ([internal]artifacts/2026-05-22-macos-install-ux-handoff.md §"Coordinates"):
        //   .app icon center: (130, 200) on the 540×380 canvas
        //   Applications shortcut center: (410, 200)
        contents: (opts) => [
          { x: 130, y: 200, type: 'file', path: opts.appPath },
          { x: 410, y: 200, type: 'link', path: '/Applications' },
        ],
        additionalDMGOptions: {
          window: {
            size: { width: 540, height: 380 },
          },
        },
      },
      ['darwin']
    ),
    new MakerDeb({
      options: {
        name: 'concord-voice',
        bin: 'concord-voice',
        productName: 'Concord Voice',
        genericName: 'Voice Communication',
        description: 'Concord Voice Desktop Client',
        productDescription: 'Privacy-first voice communication platform.',
        maintainer: 'Concord Voice Team <support@concordvoice.com>',
        homepage: 'https://concordvoice.com',
        section: 'net',
        categories: ['Network', 'Chat'],
        mimeType: ['x-scheme-handler/concord'],
        // Object form is load-bearing: electron-installer-common writes
        // hicolor theme icons only for resolution-keyed icon configs.
        icon: linuxIconConfig(),
      },
    }),
    new MakerRpm({
      options: {
        name: 'concord-voice',
        bin: 'concord-voice',
        productName: 'Concord Voice',
        genericName: 'Voice Communication',
        description: 'Concord Voice Desktop Client',
        productDescription: 'Privacy-first voice communication platform.',
        homepage: 'https://concordvoice.com',
        license: 'LicenseRef-CVSL-1.0',
        group: 'Applications/Communications',
        categories: ['Network', 'Chat'],
        mimeType: ['x-scheme-handler/concord'],
        icon: linuxIconConfig(),
      },
    }),
    new MakerAppImage({
      options: {
        bin: 'concord-voice',
        productName: 'Concord Voice',
        categories: ['Network', 'Chat'],
        icon: linuxIconConfig(),
      },
    }),
  ],
};

export default config;
