import type { ForgeConfig } from '@electron-forge/shared-types';
import { MakerNsis } from './build/makerNsis';
import { ALLOWED_WINDOWS_PUBLISHERS } from './src/shared/allowedWindowsPublishers';
import { MakerZIP } from '@electron-forge/maker-zip';
import { MakerDMG } from '@electron-forge/maker-dmg';
import { MakerDeb } from '@electron-forge/maker-deb';
import { MakerRpm } from '@electron-forge/maker-rpm';
import { MakerAppImage } from '@reforged/maker-appimage';
import { FusesPlugin } from '@electron-forge/plugin-fuses';
import { FuseVersion, FuseV1Options } from '@electron/fuses';
import fs from 'fs';

// macOS signing & notarization — active only when CI provides all required env vars.
// Local developer builds without these env vars produce unsigned .app bundles.
//
// Per the Electron Forge signing docs (https://www.electronforge.io/guides/
// code-signing/code-signing-macos), `osxSign: {}` — empty object — is the
// recommended default. @electron/osx-sign ships a tested-in-the-wild set of
// entitlements (https://github.com/electron/osx-sign/tree/main/entitlements)
// and per-file signing logic for Electron's nested helper apps. We previously
// tried overriding these defaults via `optionsForFile` + a custom entitlements
// plist and hit a silent codesign hang during outer-bundle signing; trusting
// the defaults resolves it (see issue #403 debugging history).
//
// Forge auto-detects the signing identity by scanning the keychain for a
// `Developer ID Application` cert, so the identity string does not need to
// be hardcoded as long as exactly one such cert is imported.
const macSigning: Pick<
  NonNullable<ForgeConfig['packagerConfig']>,
  'osxSign' | 'osxNotarize'
> = process.env.APPLE_API_KEY && process.env.APPLE_API_KEY_ID && process.env.APPLE_API_ISSUER
  ? {
      osxSign: {},
      osxNotarize: {
        // App Store Connect API-key notarization (#825). Replaces the
        // app-specific-password path, which silently invalidated under
        // Apple-ID 2FA events and stranded users on 0.1.29.
        // APPLE_API_KEY here is a filesystem PATH to the .p8 key file —
        // CI writes it to a temp file in a darwin-only setup step; the
        // raw .p8 contents live in the GHA secret of the same name.
        tool: 'notarytool',
        appleApiKey: process.env.APPLE_API_KEY,
        appleApiKeyId: process.env.APPLE_API_KEY_ID,
        appleApiIssuer: process.env.APPLE_API_ISSUER,
      },
    }
  : {};

// electron-updater needs app-update.yml in Resources. The file is generated
// by CI (build-desktop.yml) before packaging. Include it only when present
// so local dev builds don't fail.
const extraResource: string[] = [];
if (fs.existsSync('./app-update.yml')) {
  extraResource.push('./app-update.yml');
}
// Third-party NOTICE/attribution file (per docs/legal/dependency-license-audit.md
// F-1). MIT, BSD, Apache-2.0, ISC, MPL-2.0, and CC-BY-licensed dependencies
// require attribution in the distributed artifact. NOTICE.md lives at the
// repo root; the relative path from this file is ../../NOTICE.md. Include
// conditionally so local builds that don't have the repo-root layout don't
// fail (e.g., extracted-tarball dev workflows).
if (fs.existsSync('../../NOTICE.md')) {
  extraResource.push('../../NOTICE.md');
}
// Forensic build tag (#920 §5.13). Generated by scripts/generate-buildtag.mjs
// from CONCORD_BUILD_TAG before packaging (renamed from VITE_BUILD_TAG to
// avoid Vite's `import.meta.env` exposure path per Copilot review on PR #982).
// Absent in local dev builds → main process falls back to 'unknown'
// (see src/main/buildInfo.ts).
//
// The "packaging context" discriminator narrows the fail-loud guard below
// to actual electron-forge invocations (`electron-forge package` / `make`).
// Unit tests (e.g. `packagingIdentity.test.ts`) also import forge.config.ts
// to inspect identity fields — those imports have no `electron-forge` in
// `process.argv`, so they don't trip the guard. This avoids a self-induced
// test failure where the CI test job (CI=true, vitest loading the config)
// would otherwise throw before any test ran.
// System tray icons (#1099). Committed static assets; extraResource copies the
// directory to <Resources>/tray/ in packaged builds (consumed by
// resolveTrayIconPath in src/main/tray.ts). existsSync-guarded for consistency
// with the entries above.
if (fs.existsSync('./assets/tray')) {
  extraResource.push('./assets/tray');
}
const isForgePackaging = process.argv.some((arg) => arg.includes('electron-forge'));
if (fs.existsSync('./buildtag.json')) {
  extraResource.push('./buildtag.json');
} else if (process.env.CI === 'true' && isForgePackaging) {
  // Fail-loud in CI packaging: a production build without buildtag.json
  // ships blind to incident-response (the IPC channel returns 'unknown'
  // regardless of which release it is). The packaging workflow has a
  // dedicated `Generate buildtag.json` step that runs between `npm run
  // build` and forge make; if we're here, that step was skipped or
  // failed silently. (#920 §5.13 silent-failure-hunter F3.)
  throw new Error(
    'forge.config.ts: buildtag.json missing in CI packaging context. ' +
      'Run `npm run build:buildtag` before electron-forge make/package, or ' +
      'check that the workflow Configure-build-environment step set CONCORD_BUILD_TAG (#920 §5.13).'
  );
}
// Google OAuth non-confidential client_secret (#975). Generated by
// scripts/generate-google-client-secret.mjs before packaging. Read
// MAIN-process-only via process.resourcesPath (never renderer/VITE_).
// Absent locally → main process falls back to env GOOGLE_OAUTH_CLIENT_SECRET_DESKTOP.
if (fs.existsSync('./googleClientSecret.json')) {
  extraResource.push('./googleClientSecret.json');
} else if (process.env.CI === 'true' && process.env.GOOGLE_SSO_DESKTOP_REQUIRED === 'true') {
  throw new Error(
    'forge.config.ts: googleClientSecret.json missing in CI packaging with GOOGLE_SSO_DESKTOP_REQUIRED=true. ' +
      'Run `npm run build:gclientsecret` before forge make/package (see build-desktop.yml).'
  );
}
// concord-audiocap native addon (ADR-0043 PR 5, #3194). The .node ships OUTSIDE
// app.asar because dlopen/LoadLibrary need a real path on disk and everything
// inside the archive is virtual; the loader JS stays INSIDE it so executable code
// entering a Node-privileged process remains under
// EnableEmbeddedAsarIntegrityValidation. See the ignore lookahead below for the
// other half of that split, and note extraResource does NOT pass through the
// ignore array — which is what lets the two halves be placed independently.
//
// PLATFORM-AWARE ON PURPOSE, and this is the clause that is easy to get wrong.
// release-build is a static six-platform matrix including linux x64/arm64, and
// the addon is win32+darwin only (ADR-0043 § Consequences puts Linux/PipeWire out
// of scope). On a Linux leg the binary's ABSENCE IS CORRECT, so an unconditional
// CI hard-fail would turn a correct state into a red release.
const NATIVE_ADDON = './native/concord-audiocap/build/Release/concord_audiocap.node';
const nativeAddonExpected = process.platform === 'darwin' || process.platform === 'win32';
if (fs.existsSync(NATIVE_ADDON)) {
  extraResource.push(NATIVE_ADDON);
} else if (nativeAddonExpected && process.env.CI === 'true' && isForgePackaging) {
  // Fail-loud, following the buildtag.json idiom above. Without this the
  // existsSync guard ALONE ships nothing, on every platform, with every leg
  // green — the packaging equivalent of a silent no-op, and precisely the defect
  // #3194 exists to close. The build-desktop.yml step that produces this file is
  // "Build the native addon (win32/darwin only)"; if we are here, it did not run.
  throw new Error(
    'forge.config.ts: concord_audiocap.node missing in CI packaging context. ' +
      'Run `npm run build:native` before electron-forge make/package — see the ' +
      '"Build the native addon" step in build-desktop.yml (#3194).'
  );
}

const linuxIconConfig = () => ({
  '128x128': './build/icons/128x128.png',
  '256x256': './build/icons/256x256.png',
  '512x512': './build/icons/512x512.png',
});

const config: ForgeConfig = {
  packagerConfig: {
    asar: {
      // Source maps must NOT ship to end users — they expose full source code and
      // any secrets or logic embedded in it. That exclusion is `ignore` below;
      // this block is about what stays OUTSIDE the archive.
      //
      // NEVER SET `unpack` OR `unpackDir` HERE. The blocker below is PERMANENT —
      // it is not waiting on a fix, and #3194 routed around it rather than
      // clearing it. (Full route ruling in the block further down.)
      // Both options are currently NON-FUNCTIONAL in this repo, and the failure is
      // a packaging crash rather than a silent no-op:
      //
      //     TypeError: (0 , minimatch_1.default) is not a function
      //         at shouldUnpackPath (@electron/asar/lib/asar.js:147)   // via `unpack`
      //         at isUnpackedDir     (@electron/asar/lib/asar.js:54)   // via `unpackDir`
      //
      // TWO frames, because the two options crash in different places and the
      // single frame recorded here originally would not reproduce for whoever
      // tried `unpackDir`. Setting `unpackDir` ALONE leaves `unpack` undefined, so
      // :147 is guarded by `if (unpack)` and never runs — the throw comes from
      // isUnpackedDir at :54, and only once its `startsWith` short-circuit fails.
      //
      // @electron/asar@3.4.1 declares minimatch ^3.0.4 and calls its DEFAULT
      // export. This package overrides minimatch globally to ^10.2.6, and
      // minimatch dropped the default export at 9 — it exports { minimatch }. So
      // `shouldUnpackPath` throws for any non-empty glob. The code path is only
      // reached when one of these options is set, which is why nothing noticed:
      // both have been `undefined` for the life of the override.
      //
      // The minimatch override is NOT the thing to change. It is security-
      // validated (see the //overrides_security note in package.json — it clears
      // four advisory floors), its governing principle is that every skew is
      // UPWARD, and client/admin explicitly recorded "Do not re-add a minimatch
      // pin below 10" in PR #2715. Capping asar back to minimatch 3 to make an
      // unpack glob work would invert all of that.
      //
      // ADR-0043 D1 needs a .node OUTSIDE the archive — dlopen/LoadLibrary needs a
      // real path on disk and everything inside app.asar is virtual.
      //
      // ROUTE CHOSEN, PR 5 / #3194: ship it via `extraResource`, which this config
      // already uses for five other payloads and which does NOT pass through the
      // ignore array. It touches no dependency at all. See the extraResource block
      // above for the push and its platform-aware CI guard.
      //
      // Rejected, and CLOSED rather than pending:
      //   1. Override @electron/asar to ^4.3.0 (declares minimatch ^10.0.1). Fixes
      //      it at the source and the skew is upward — but @electron/packager@18.4.4
      //      declares ^3.2.13, so it forces a MAJOR onto the release packaging path
      //      to buy what extraResource already provides.
      //   3. Wait for @electron/packager to move to asar 4 — no owner, and it would
      //      block the whole epic indefinitely.
      //   4. Forge's plugin-auto-unpack-natives — it writes this same `asar.unpack`
      //      key, so it hits the identical crash. Also not installed, making it a
      //      new dependency against D1's own supply-chain reasoning.
      //
      // Electron's own asar docs name `--unpack *.node` as the canonical way to ship
      // a native module. We deliberately diverge, because in THIS repo it does not
      // run. Recorded so the next reader does not find those docs, reach for
      // `unpack`, and rediscover the crash above.
      unpackDir: undefined,
    },
    // Only four things belong in the archive: `dist/` (built main, preload and
    // renderer — everything resolves relative to `__dirname` inside it), the
    // dev-pruned `node_modules/`, `package.json`, and exactly two icons under
    // `build/` (see the build/ rule below). @electron/packager's
    // DEFAULT_IGNORES cover just lockfiles, `.git`, `node_modules/.bin`, `.o`
    // files and the `out/` directory — NOT an app's own source tree — so
    // without the entries below the whole working directory ships inside
    // app.asar: `src/`, the whole test suite, and any untracked `.env` a
    // developer happens to have sitting there.
    //
    // Each path is tested app-dir-relative with a leading slash ('/src/main.ts')
    // through String.prototype.match, which is UNANCHORED. Every PATH pattern
    // is therefore `^`-anchored so it cannot also strike a production
    // dependency under /node_modules/ — an unanchored /tests/ would gut every
    // packaged module that ships its own tests directory. The two SUFFIX rules
    // (/\.map$/, /\.d\.[cm]?ts$/) are the deliberate exceptions: both name file
    // kinds that are compile-time-only wherever they appear, so reaching into
    // dependencies is the point rather than the hazard.
    ignore: [
      /\.map$/,
      // TypeScript declarations. `tsconfig.main.json` inherits declaration +
      // declarationMap from tsconfig.json, so `npm run build:main` emits
      // dist/**/*.d.ts beside the .js it actually runs; /\.map$/ took their
      // .d.ts.map companions and left the declarations behind. Nothing loads a
      // .d.ts at runtime — they are compile-time only — so like /\.map$/ this
      // is deliberately a SUFFIX rule rather than an ^-anchored one: it also
      // strips the declarations shipped by production dependencies, which are
      // the overwhelming majority (957 of 1035 entries, ~13.4 MiB, against 78
      // and ~133 KiB from dist/). The [cm]? covers TypeScript's `.d.cts` and
      // `.d.mts` variants, which are NOT a hypothetical: 127 of them (~4.96 MiB)
      // survived the first `.d.ts`-only draft, from dual-published dependencies
      // such as zod, lucide-react and minisearch. Nothing runtime is caught —
      // Node executes `.cjs`/`.mjs`, never `.cts`/`.mts` — and in the packaged
      // tree every single `.cts` and `.mts` entry was in fact a declaration
      // (108 of 108 and 19 of 19), but the pattern still matches only the
      // `.d.` form so a genuine TypeScript source file could never be caught.
      //
      // Verified before widening it to node_modules: no shipped package
      // resolves a runtime entry point to a .d.ts. The single apparent
      // counter-example is upstream mediasoup-client, whose "./enhancedEvents"
      // export map reads `"ortc": "./lib/enhancedEvents.d.ts"` where it means
      // `"types"` — a copy-paste slip from the "./ortc" entry above it. `ortc`
      // is not a Node export condition, so resolution skips the key and falls
      // through to `"default": "./lib/enhancedEvents.js"`.
      /\.d\.[cm]?ts$/,
      // Sources plus build-time-only and report-output trees. Two of these are
      // duplicates rather than dead weight: `public/` is copied into
      // dist/renderer by Vite, and `assets/tray` reaches <Resources>/tray via
      // extraResource (resolveTrayIconPath reads process.resourcesPath when
      // packaged, and cwd/assets only in dev).
      /^\/(src|tests|docs|scripts|schemas|functions|public|assets|coverage|playwright-report|test-results|spikes)($|\/)/,
      // `spikes` was added by the payload-boundary guard's own finding on PR
      // #3155: it was shipping its full source into app.asar. It is a throwaway
      // Windows measurement probe (s2probe.cpp and its WAV output) that has no
      // business in a user's install at all.
      //
      // `native` was in that same alternation until ADR-0043 PR 5 (#3194), which
      // needed ONE file out of it. The addon SOURCE still goes nowhere near the
      // archive — C++, binding.gyp, tests, the fuzzer, none of which runs at
      // runtime — but the loader `index.js` now ships INSIDE it, so executable JS
      // entering a Node-privileged process stays under
      // EnableEmbeddedAsarIntegrityValidation. The opaque .node goes the OTHER
      // way, via extraResource, because dlopen and LoadLibrary need a real path
      // and everything inside app.asar is virtual.
      //
      // BOTH DIRECTORY LEVELS MUST BE ADMITTED, and this is the whole reason the
      // rule is a lookahead rather than another alternation arm. The copy filter
      // is asked about a directory BEFORE it descends, so a pattern matching
      // `/native` or `/native/concord-audiocap` suppresses the entire subtree and
      // index.js is never copied — with every per-file assertion still green.
      // `^\/native\/` cannot match `/native` at all, and the lookahead's
      // `concord-audiocap$` arm covers the second level.
      //
      // Do NOT "fix" this by dropping the rule: that ships the whole addon source.
      // Do NOT widen it past index.js either — the archive's top-level set is an
      // asserted invariant (see verify-asar-payload.sh and [internal]rules/electron.md
      // § app.asar payload boundary), and the verifier's depth check will red.
      /^\/native\/(?!concord-audiocap($|\/index\.js$))/,
      // `build/` is ALMOST all packaging-time input the makers read from the
      // source directory — but not quite, so it cannot be excluded wholesale.
      // Two files are read from inside the archive at runtime via
      // app.getAppPath():
      //   src/main/main.ts                 -> build/icon.png   (packaged-only
      //                                       splash, `if (app.isPackaged)`)
      //   src/main/applicationsFolderGate.ts -> build/icon.icns (macOS
      //                                       move-to-Applications dialog)
      // Both call nativeImage.createFromPath, which NEVER throws: a missing
      // file yields an empty image and the surfaces silently lose their
      // branding in release builds only. Keep exactly those two and drop the
      // rest (splash.gif, icon.ico, dmg backgrounds, icons/, makerNsis.ts,
      // installer.nsh). The pattern deliberately does not match the bare
      // `/build` directory entry — the copy filter is asked about a directory
      // before it descends, so excluding it would prevent the icons from ever
      // being copied.
      /^\/build\/(?!icon\.(?:png|icns)$)/,
      // Every root dotfile, which is how all four `.env` variants are caught.
      // `.env.staging` was shipping an internal LAN address to end users, and
      // an untracked local `.env` would ship whatever it holds.
      /^\/\.[^/]+$/,
      // Root-level tooling config and docs.
      /^\/(tsconfig[^/]*\.json|[^/]+\.config\.[cm]?[jt]s|index\.html|README\.md|wrangler\.toml)$/,
    ],
    name: 'Concord Voice',
    // Per-platform executable name (#1077 follow-up).
    //
    // macOS / Windows: use the proper display name 'Concord Voice'. This is
    // what users see in Activity Monitor (macOS), Task Manager (Windows), and
    // crash reports — proper-name format is the user-facing expectation on
    // those platforms.
    //
    // Linux: fall back to kebab-case 'concord-voice'. Two structural reasons:
    //   (1) debian-policy §5.6.7 expects lowercase alphanumeric + hyphens for
    //       binary names placed under /usr/bin/. Spaces work in the filesystem
    //       but break shell completion, $PATH lookups, and most process-
    //       management scripts.
    //   (2) @reforged/maker-appimage's `bin:` option performs a literal-string
    //       file lookup inside the packaged app directory. With
    //       `bin: 'concord-voice'` (the Linux convention we keep in the Deb /
    //       Rpm / AppImage maker configs below) but executableName set to
    //       'Concord Voice', the lookup fails at make-time with "Could not
    //       find executable 'concord-voice' in packaged application." Aligning
    //       executableName to bin on Linux closes that gap.
    //
    // `process.platform` reflects the BUILDER's OS, not the target. This is
    // correct in CI (each platform builds on its native runner per
    // build-desktop.yml: ubuntu-latest for Linux, macos-latest for macOS,
    // windows-latest for Windows). It would break for cross-compilation
    // (e.g., `electron-forge make --platform=linux` on macOS would produce a
    // Linux package with executableName='Concord Voice' because the builder
    // is macOS). Cross-compilation isn't used by the project; if that
    // changes, refactor to derive the target from argv instead.
    executableName: process.platform === 'linux' ? 'concord-voice' : 'Concord Voice',
    icon: './build/icon',
    appBundleId: 'com.concordvoice.desktop',
    protocols: [{ name: 'Concord Voice invite links', schemes: ['concord'] }],
    appCopyright: 'Copyright © 2026 Concord Voice LLC',
    appCategoryType: 'public.app-category.social-networking',
    win32metadata: {
      CompanyName: 'Concord Voice LLC',
      FileDescription: 'Concord Voice Desktop Client',
      ProductName: 'Concord Voice',
    },
    extraResource,
    ...macSigning,
    darwinDarkModeSupport: true,
    extendInfo: {
      CFBundleURLTypes: [
        {
          CFBundleURLName: 'Concord Voice invite links',
          CFBundleURLSchemes: ['concord'],
        },
      ],
      NSMicrophoneUsageDescription:
        'Concord Voice needs microphone access for voice calls and audio communication.',
      NSCameraUsageDescription: 'Concord Voice needs camera access for video calls.',
      // macOS 14.2+ routes desktop audio capture through Apple's CoreAudio Tap API.
      // WITHOUT this key capture yields a live-but-SILENT track -- no exception, no
      // warning -- so captureScreenElectron's try/catch video-only fallback never
      // fires and the client publishes silence to the SFU. See ADR-0043 D7.
      NSAudioCaptureUsageDescription:
        'Concord Voice needs system audio access to share your screen with sound.',
    },
  },
  makers: [
    // Windows: NSIS, not Squirrel.Windows (#2402). Squirrel's Setup.exe
    // recursive-deletes its own install root before writing, which meant deleting
    // the very installer executing from %LOCALAPPDATA%\ConcordVoice\pending\ —
    // Windows locks a running image, so the delete threw UnauthorizedAccessException
    // and the installer died. Confirmed across three trials on a live Windows box.
    // electron-builder also documents Squirrel.Windows as unsupported by
    // electron-updater, which is what we use to deliver updates.
    //
    // MakerNsis is local (build/makerNsis.ts) because the published
    // electron-forge-maker-nsis is Forge-5-era and throws under Forge 7.
    new MakerNsis({
      appId: 'com.concordvoice.desktop',
      productName: 'Concord Voice',
      // IMPORTED, not duplicated. scripts/generate-app-update.mts spreads this same
      // constant into app-update.yml's publisherName, and electron-updater reads the
      // Windows allowlist ONLY from that on-disk file — so if the installer were
      // stamped with a different name than the file, install-time Authenticode
      // verification would silently stop matching (#2020).
      //
      // A hardcoded literal here would make that divergence possible AND invisible:
      // a cert-rotation LLC rename (the case allowedWindowsPublishers.ts exists to
      // handle) would update the constant and app-update.yml while this file kept
      // stamping the old name, with every test still green.
      publisherName: [...ALLOWED_WINDOWS_PUBLISHERS],
      nsis: {
        oneClick: true,
        perMachine: false,
        // Pins $INSTDIR to $LOCALAPPDATA\ConcordVoice\app so the install root and
        // the updater cache (…\ConcordVoice\pending) are SIBLINGS that cannot
        // destroy each other. Without it, app-builder-lib takes the sanitizedName
        // branch (targetUtil.js:40) and installs to a directory derived from
        // @concordvoice/desktop.
        include: './build/installer.nsh',
        // build-desktop.yml:1163 globs *Setup.exe; electron-builder's default
        // artifactName does not end in Setup.exe and would fail the release
        // signature-verification step.
        artifactName: 'ConcordVoiceSetup.exe',
        // NSIS is differential-aware by default and would emit
        // ConcordVoiceSetup.exe.blockmap into out/make. That name matches no branch in
        // build-desktop.yml's artifact-normalization case, so it would fall to the
        // catch-all un-renamed — and then be picked up by the `-name "*.blockmap"`
        // release attach glob with the SAME basename from both the x64 and arm64 legs,
        // colliding on upload. Windows has no differential-download path today anyway
        // (latest.yml carries no blockMapSize for win32), so this costs nothing.
        differentialPackage: false,
        installerIcon: './build/icon.ico',
        uninstallerIcon: './build/icon.ico',
      },
    }),
    new MakerZIP({}, ['darwin']),
    // DMG installer (#1159 Phase 1) — branded drag-to-Applications experience.
    // ZIP above remains the canonical artifact for electron-updater's auto-update
    // chain (see latest-mac.yml generator in .github/workflows/build-desktop.yml).
    // The .dmg is install-only; do NOT add it to the latest-mac.yml glob.
    new MakerDMG(
      {
        background: './build/dmg-background.png',
        icon: './build/icon.icns',
        format: 'ULFO',
        // Icon centers per design handoff spec
        // ([internal]artifacts/2026-05-22-macos-install-ux-handoff.md §"Coordinates"):
        //   .app icon center: (130, 200) on the 540×380 canvas
        //   Applications shortcut center: (410, 200)
        contents: (opts) => [
          { x: 130, y: 200, type: 'file', path: opts.appPath },
          { x: 410, y: 200, type: 'link', path: '/Applications' },
        ],
        additionalDMGOptions: {
          window: {
            size: { width: 540, height: 380 },
          },
        },
      },
      ['darwin']
    ),
    new MakerDeb({
      options: {
        name: 'concord-voice',
        bin: 'concord-voice',
        productName: 'Concord Voice',
        genericName: 'Voice Communication',
        description: 'Concord Voice Desktop Client',
        productDescription: 'Privacy-first voice communication platform.',
        maintainer: 'Concord Voice Team <support@concordvoice.com>',
        homepage: 'https://concordvoice.com',
        section: 'net',
        categories: ['Network', 'Chat'],
        mimeType: ['x-scheme-handler/concord'],
        // Object form is load-bearing: electron-installer-common writes
        // hicolor theme icons only for resolution-keyed icon configs.
        icon: linuxIconConfig(),
      },
    }),
    new MakerRpm({
      options: {
        name: 'concord-voice',
        bin: 'concord-voice',
        productName: 'Concord Voice',
        genericName: 'Voice Communication',
        description: 'Concord Voice Desktop Client',
        productDescription: 'Privacy-first voice communication platform.',
        homepage: 'https://concordvoice.com',
        license: 'LicenseRef-CVSL-1.0',
        group: 'Applications/Communications',
        categories: ['Network', 'Chat'],
        mimeType: ['x-scheme-handler/concord'],
        icon: linuxIconConfig(),
      },
    }),
    new MakerAppImage({
      options: {
        bin: 'concord-voice',
        productName: 'Concord Voice',
        categories: ['Network', 'Chat'],
        icon: linuxIconConfig(),
      },
    }),
  ],
  plugins: [
    new FusesPlugin({
      version: FuseVersion.V1,
      [FuseV1Options.RunAsNode]: false,
      [FuseV1Options.EnableNodeCliInspectArguments]: false,
      [FuseV1Options.EnableEmbeddedAsarIntegrityValidation]: true,
      [FuseV1Options.OnlyLoadAppFromAsar]: true,
      [FuseV1Options.EnableCookieEncryption]: true,
    }),
  ],
};

export default config;
